# Generated by Django 4.2.5 on 2024-01-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0003_transaction_status_transaction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Captured'), ('completed', 'Authorized'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
